version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
      - 8000:8000
      - 8080:80
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
